# Generated by Django 5.0.1 on 2024-04-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_user_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
    ]
