# Generated by Django 5.0.1 on 2024-04-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_age_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=(), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default=(), max_length=100),
            preserve_default=False,
        ),
    ]
