# Generated by Django 5.0.1 on 2024-04-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_age_profile_password_profile_profession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
